version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: 3
  commands:
    - pip install hatch
    - hatch run docs:build
    - mkdir --parents $READTHEDOCS_OUTPUT
    - mv doc/build/html $READTHEDOCS_OUTPUT/html
